[profile.default]
# Project layout
src = "."
libs = ["library"]
script = "script"
test = "."
out = "artifact"
# Solidity compiler
remappings = [
  "forge-std/=library/forge-std/src/",
  "util/=library/util/"
]
deny_warnings = true
