[profile.default]
# Project layout
libs = ["library"]
src = "."
test = "."
script = "."
out = "artifact"
# Solidity compiler
remappings = [
  "forge/=library/forge-std/src/",
  "chainlink/=library/chainlink-local/",
  "util/=library/util/"
]
deny_warnings = true
